# Generated by Django 3.0.8 on 2020-08-05 15:31

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion

import csv

def import_ingredients(apps, schema_editor):
    Ingredient = apps.get_model('catering', 'Ingredient')
    with open('apps/catering/ingredients.csv', encoding='utf-8') as f:
        reader = csv.reader(f)
        next(reader)
        for row in reader:
            Ingredient.objects.create(name=row[0], callories=int(row[1]))

# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:
# config.migrations.catering.0008_auto_20200802_1953

class Migration(migrations.Migration):

    replaces = [('catering', '0001_initial'), ('catering', '0002_auto_20200730_1903'), ('catering', '0003_auto_20200730_1936'), ('catering', '0004_auto_20200730_1937'), ('catering', '0005_dish_ingredient'), ('catering', '0008_auto_20200802_1953'), ('catering', '0007_auto_20200802_1949'), ('catering', '0009_merge_20200802_1954'), ('catering', '0010_auto_20200803_1834'), ('catering', '0011_auto_20200803_1839'), ('catering', '0012_auto_20200803_1840'), ('catering', '0013_auto_20200803_1844'), ('catering', '0014_auto_20200803_1912'), ('catering', '0015_auto_20200803_1913'), ('catering', '0016_dish_place'), ('catering', '0017_auto_20200804_2124'), ('catering', '0018_auto_20200804_2138'), ('catering', '0019_auto_20200805_1929')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Establishment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='place_photos')),
                ('address', models.CharField(blank=True, max_length=150)),
                ('avg_cost', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8)),
                ('coordinates', models.CharField(blank=True, max_length=30)),
                ('owner', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('work_time', models.CharField(blank=True, help_text='Введите время работы заведения в формате "С XX до YY"', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='dish_photos')),
                ('total_callories', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8)),
                ('ingredients', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50), size=None), size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('callories', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
            ],
        ),
        migrations.RunPython(
            import_ingredients,
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='dish',
            name='ingredients',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(blank=True), size=None), size=None),
        ),
        migrations.AlterField(
            model_name='dish',
            name='ingredients',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(blank=True), size=None),
        ),
        migrations.AlterField(
            model_name='dish',
            name='ingredients',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(blank=True), size=None), size=None),
        ),
        migrations.AlterField(
            model_name='dish',
            name='ingredients',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(blank=True), size=None),
        ),
        migrations.AlterField(
            model_name='dish',
            name='total_callories',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='dish',
            name='total_callories',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='dish',
            name='place',
            field=models.ManyToManyField(related_name='places', to='catering.Establishment'),
        ),
    ]
