# Generated by Django 3.0.8 on 2020-07-22 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='test',
            options={'ordering': ['id'], 'verbose_name': 'Тест', 'verbose_name_plural': 'Тест'},
        ),
    ]
